
spring:
  datasource:
    username: postgres
    password: Manifest
    url: jdbc:postgresql://postgres-db:5432/userDB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: employee-management

server:
  error:
    include-exception: true
    include-stacktrace: always
  port: 8060
